name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14.x'
    - name: Build
      run: |
        npm i typescript
        tsc -p ts/tsconfig.json
        rm wwwroot/.gitignore
    - name: Deploy with gh-pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: wwwroot
